from zope.interface import Interface

class IPloneGlobals(Interface):

    def utool():
        """ """
    def portal():
        """ """
    def portal_url():
        """ """
    def mtool():
        """ """
    def gtool():
        """ """
    def atool():
        """ """
    def aitool():
        """ """
    def putils():
        """ """
    def wtool():
        """ """
    def ifacetool():
        """ """
    def syntool():
        """ """
    def portal_title():
        """ """
    def object_title(self):
        """ """
    def member(self):
        """ """
    def checkPermission(self):
        """ """
    def membersfolder(self):
        """ """       
    def isAnon(self):
        """ """       
    def actions(self):
        """ """       
    def keyed_actions(self):
        """ """
    def user_actions(self):
        """ """
    def workflow_actions(self):
        """ """
    def folder_actions(self):
        """ """
    def global_actions(self):
        """ """
    def portal_tabs(self):
        """ """
    def wf_state(self):
        """ """
    def portal_properties(self):
        """ """
    def site_properties(self):
        """ """
    def ztu(self):
        """ """
    def actions(self):
        """ """
    def wf_actions(self):
        """ """
    def isFolderish(self):
        """ """
    def template_id(self):
        """ """
    def slots_mapping(self):
        """ """
    def Iterator(self):
        """ """
    def tabindex(self):
        """ """
    def here_url(self):
        """ """
    def sl(self):
        """ """
    def sr(self):
        """ """
    def hidecolumns(self):
        """ """
    def default_language(self):
        """ """
    def language(self):
        """ """
    def language(self):
        """ """
    def is_editable(self):
        """ """
    def isEditable(self):
        """ """
    def lockable(self):
        """ """
    def isLocked(self):
        """ """
    def isRTL(self):
        """ """
    def visible_ids(self):
        """ """
    def current_page_url(self):
        """ """

