## Script (Python) "document_edit"
##parameters=text_format, field_text, file='', SafetyBelt='', choice=' Change ', field_title='', field_description='', field_id=''
##title=Edit a document

REQUEST=context.REQUEST

errors=context.validate_document_edit(file=file)
if errors:
    edit_form=getattr(context, context.getTypeInfo().getActionById( 'edit'))
    return edit_form()

filename=getattr(file, 'filename', '')
if file and filename and context.isIDAutoGenerated(field_id):
    id=filename[max( string.rfind(filename, '/')
                   , string.rfind(filename, '\\')
                   , string.rfind(filename, ':') )+1:]

if file and filename:
    file.seek(0)

context.edit( text_format
            , field_text
            , file=file
            , safety_belt=SafetyBelt
            )

context.plone_utils.contentEdit(context,
                                id=field_id,
                                description=field_description)

qst='portal_status_message=Document+changed.'

context.REQUEST.RESPONSE.redirect( '%s/%s?%s' % ( context.absolute_url()
                                                , context.getTypeInfo().getActionById( 'view' )
                                                , qst
                                                ) )



