## Script (Python) "file_edit"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=precondition='', field_file='', field_id='', title=None, description=None, file_data=''
##title=Edit a file
##
from Products.CMFPlone import StringIO
REQUEST=context.REQUEST

if not field_id:
    field_id=context.getId()
    REQUEST.set('field_id', field_id)

file=field_file
id=field_id

if file_data and not hasattr(field_file, 'filename'):
    file=StringIO(file_data)

context.edit( precondition=precondition,
              file=file )

errors=context.validate_file_edit()
if errors:
    form=getattr( context, context.getTypeInfo().getActionById( 'edit' ) )
    return form()

filename=file.filename
if context.isIDAutoGenerated(id) and filename:
    if filename.find('\\') > -1: # winXX      
        id=filename.split('\\')[-1]
    else:
        id=filename.split('/')[-1] # *nix

if not context.isIDAutoGenerated(id):   
    context.REQUEST.set('id', id)

qst='portal_status_message=File+has+changed.'
REQUEST.set('portal_status_message','File+has+changed.')

if hasattr(context, 'extended_edit'):
    edit_hook=getattr(context, 'extended_edit')
    response=edit_hook(redirect=0)
    if response:
        return response
context.rename_object(redirect=0, id=id)

target_action = context.getTypeInfo().getActionById( 'view' )
context.REQUEST.RESPONSE.redirect( '%s/%s?%s' % ( context.absolute_url()
                                                , target_action
                                                , qst
                                                ) )
