## Script (Python) "file_edit"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=precondition='', file='', id='', title=None, description=None, file_data=''
##title=Edit a file
##

# if there is no id or an autogenerated id, use the filename as the id
# if not id or context.isIDAutoGenerated(id):
# 

filename=getattr(file,'filename', '')
if file and filename:
    if not id:
        id = filename[max( string.rfind(filename, '/')
                       , string.rfind(filename, '\\')
                       , string.rfind(filename, ':') )+1:]

    file.seek(0)

# if there is no id specified, keep the current one
# if we already have a non-autogenerated id - it may
# be in use.. we will keep the current id.

if not id or not context.isIDAutoGenerated(id):
    id = context.getId()

new_context = context.portal_factory.doCreate(context, id)
new_context.edit( precondition=precondition
                , file=file )
new_context.plone_utils.contentEdit( new_context
                                   , id=id
                                   , description=description )

return ('success', new_context, {'portal_status_message':context.REQUEST.get('portal_status_message', 'File changes saved.')})

