## Script (Python) "image_edit"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=precondition='', file='', id='', title=None, description=None
##title=Edit an image
##
filename=getattr(file,'filename', '')
if file and filename:
#    # if there is no id or an autogenerated id, use the filename as the id
#    if not id or context.isIDAutoGenerated(id):
    # if there is no id, use the filename as the id
    if not id:
        id = filename[max( string.rfind(filename, '/')
                       , string.rfind(filename, '\\')
                       , string.rfind(filename, ':') )+1:]

    file.seek(0)

# if there is no id specified, keep the current one
if not id:
    id = context.getId()

new_context = context.portal_factory.doCreate(context, id)
new_context.edit( precondition=precondition
                , file=file )
new_context.plone_utils.contentEdit( new_context
                                   , id=id
                                   , description=description )
return ('success', new_context, {'portal_status_message':context.REQUEST.get('portal_status_message', 'Image changes saved.')})
