## Script (Python) "isIDAutoGenerated"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=id=None
##title=
##
from DateTime import DateTime

#we are looking for ids that are Type(),YYYY/MM/DD,random_number()

if id is None: 
    id=context.getId()
try:
    obj_type, date_created, random_number = id.split('.')

    if ' '.join(obj_type.split('_'))==context.getTypeInfo().getId() and \
       DateTime(date_created) and \
       float(random_number):
        return 1
except:
    return 0

