## Script (Python) "isIDAutoGenerated"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=id=None
##title=
##
#autogenerated Ids look like $portal_type.YYYY-MM-DD.integer(random number)

putils = context.plone_utils

if id is None:
    id=context.getId()

context.plone_log('The script isIDAutoGenerated is deprecated, please use the PloneTool method of the same name.')

return putils.isIDAutoGenerated(id)