## Script (Python) "isIDAutoGenerated"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=pos=0, upper=100000
##title=

from Products.CMFPlone import IndexIterator
return IndexIterator(pos=pos, upper=upper)
