## Script (Python) "show_id"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=
##title=Determine whether to show an id in an edit form
if context.isIDAutoGenerated(context.getId()):
    return not (context.portal_factory.isTemporary(context) or context.CreationDate() == context.ModificationDate())
return 1
