## Script (Python) "folder_edit"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=field_title, field_description, choice=' Change ', field_id=''
##title=Edit a folder (Plonized)
##
REQUEST=context.REQUEST
destination_url=context.absolute_url()
id=field_id

errors=context.validate_folder_edit()
if errors:
    edit_form=getattr(context, context.getTypeInfo().getActionById( 'edit'))
    return edit_form()

title, description=field_title, field_description
context.edit( title=title,
              description=description)

qst='portal_status_message=Folder+changed.'
target_action='folder_contents'

if not context.isIDAutoGenerated(id) and context.isIDAutoGenerated(context.getId()):
    context.aq_parent.manage_renameObject( context.getId(), id, REQUEST)
    destination_url=REQUEST['URL2']+'/'+id

REQUEST.RESPONSE.redirect( '%s/%s?%s' % ( destination_url
                                    , target_action
                                    , qst
                                    ) )
