#!/bin/sh -e
#----------------------------------------------------------------
# Simple `.config' script for zope-* packages.
# First coded by Luca - De Whiskey's - De Vitis <luca@debian.org>
#----------------------------------------------------------------

# Load the confmodule.
. /usr/share/debconf/confmodule

# Setup.
db_version 2.0
db_capb backup

# Prompt the question to the user.
db_input low "$(basename $0 .config)/postinst" || true
db_go

# Stop the communication with the db.
db_stop

# That's all folks!
exit 0
