#! /bin/sh
#----------------------------------------------------------------
# Simple `.postinst' script for zope-* packages.
# First coded by Luca - De Whiskey's - De Vitis <luca@debian.org>
#----------------------------------------------------------------

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see /usr/doc/packaging-manual/
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.

# Load confmodule.
. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
    configure)
		# Get the answer.
		db_get "$(basename $0 .postinst)/postinst" || true
		test "$RET" = "true" && /etc/init.d/zope restart
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

# Stop the communication with the db.
db_stop

#DEBHELPER#

# That's all folks!
exit 0
