(function($){

function refreshPortlet(hash, _options){
    var options = {
        data: {},
        success: function(){},
        error: function(){},
        ajaxOptions: {}};
    $.extend(options, _options);
    options.data.portlethash = hash;
    ajaxOptions = options.ajaxOptions;
    ajaxOptions.url = $('base').attr('href') + '/@@render-portlet';
    ajaxOptions.success = function(data){
        var container = $('[data-portlethash="' + hash + '"]');
        var portlet = $(data);
        container.html(portlet);
        $('#kss-spinner').hide();
        options.success(data, portlet);
    }
    ajaxOptions.error = function(){
        $('#kss-spinner').hide();
        options.error();
    }
    ajaxOptions.data = options.data;
    $.ajax(ajaxOptions);
}

/* Calendar Portlet KSS Replacement */
$('#calendar-next,#calendar-previous').live('click', function(){
    $('#kss-spinner').show();
    var el = $(this);
    var container = el.parents('.portletWrapper');
    refreshPortlet(container.data('portlethash'), {
        data: {
            month: el.data('month'),
            year: el.data('year')
        }
    });
    return false;
});

/* apply a refresh timeout to a portlet */
function applyPortletTimeout(portlet){
    var timeout = portlet.data('timeout');
    if(timeout == undefined){
        timeout = 30; // Default to 30 seconds
    }else{
        timeout = parseInt(timeout);
    }
    timeout = timeout * 1000;
    setTimeout($.proxy(function(){
        refreshPortlet(this.parents('.portletWrapper').data('portlethash'), {
            success: function(data, portlet){
                apply_timeout(portlet);
            }
        });
    }, portlet), timeout);
}

/* reload folder contents listings */
function replaceFolderContentsTable(overrides, prevent) {
    var fCF = $("form[name=folderContentsForm]");
    var defaults = {
        "sort_on": fCF.find("input[name=sort_on]").first().val(),
        "pagenumber": fCF.find("input[name=pagenumber]").first().val(),
        "show_all": fCF.find("input[name=show_all]").first().val()
    };
    $.get('foldercontents_get_table', $.extend(defaults, overrides), function(data) {
        $("#folderlisting-main-table").replaceWith(data);
        // fix up links generated by batching
        var orig_template = $("form[name=folderContentsForm] input[name=orig_template]").first().val();
        $("div.listingBar a").each(function(){
            $(this).attr("href", $(this).attr("href").replace(/foldercontents_get_table/, orig_template));
        });
    });
}

/* dom loaded related actions */
$(document).ready(function(){
    /* Any portlets with the class kssPortletRefresh(deprecated)
       or refreshPortlet will automatically be refreshed with this.
       Data attribute timeout(data-timeout) will be used to override
       the timeout used for the refresh */
    $('.kssPortletRefresh,.refreshPortlet').each(function(){
        applyPortletTimeout($(this));
    });

    /* deferred rendering portlets */
    $('.portlet-deferred').each(function(){
        refreshPortlet($(this).parents('.portletWrapper').data('portlethash'));
    });

    /* folder contents table loading actions */
    if($("body.template-folder_contents").length) {
        var ccore = $("#content-core");
        ccore.delegate("#foldercontents-show-all", "click", function(event) {
            event.preventDefault();
            replaceFolderContentsTable({ "show_all": "True", "pagenumber": "1" });
        });
        ccore.delegate("#foldercontents-show-batched", "click", function(event) {
            event.preventDefault();
            replaceFolderContentsTable({ "show_all": "False" });
        });
        ccore.delegate("#foldercontents-title-column", "click", function(event) {
            replaceFolderContentsTable({ "sort_on": "sortable_title" });
        });
        ccore.delegate("#foldercontents-modified-column", "click", function(event) {
            replaceFolderContentsTable({ "sort_on": "modified" });
        });
        ccore.delegate("#foldercontents-status-column", "click", function(event) {
            replaceFolderContentsTable({ "sort_on": "review_state" });
        });
        ccore.delegate("#foldercontents-selectall", "click", function(event) {
            event.preventDefault();
            replaceFolderContentsTable({ "select": "screen" });
        });
        ccore.delegate("#foldercontents-selectall-completebatch", "click", function(event) {
            event.preventDefault();
            replaceFolderContentsTable({ "select": "all" });
        });
        ccore.delegate("#foldercontents-clearselection", "click", function(event) {
            event.preventDefault();
            replaceFolderContentsTable({ "select": "none" });
        });
        ccore.delegate("div.listingBar a", "click", function(event) {
            event.preventDefault();
            var link = $(this).attr("href");
            var page = decodeURI((RegExp("pagenumber\:int" + '=' + '(.+?)(&|$)').exec(link)||[,null])[1]);
            replaceFolderContentsTable({ "pagenumber": page });
        });
    }

});

})(jQuery);
